spring.application.name=jwtToken

spring.datasource.url=jdbc:postgresql://localhost:5431/securitydb
spring.datasource.password=secret
spring.datasource.username=postgres
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem